/* eslint-disable no-dupe-keys */
// Traducciones de idiomas al español
export const languageNamesES = {
	Afar: "Afar",
	Abkhazian: "Abjasio",
	Avestan: "Avéstico",
	Afrikaans: "Afrikáans",
	Akan: "Akan",
	Amharic: "Amhárico",
	Aragonese: "Aragonés",
	Arabic: "Árabe",
	Assamese: "Asamés",
	Avaric: "Avaric",
	Aymara: "Aimara",
	Azerbaijani: "Azerbaiyano",
	Bashkir: "Baskir",
	Belarusian: "Bielorruso",
	Bulgarian: "Búlgaro",
	Bihari: "Bihari",
	Bislama: "Bislama",
	Bambara: "Bambara",
	Bengali: "Bengalí",
	Tibetan: "Tibetano",
	Breton: "Bretón",
	Bosnian: "Bosnio",
	Catalan: "Catalán",
	Chechen: "Checheno",
	Chamorro: "Chamorro",
	Corsican: "Corso",
	Cree: "Cree",
	Czech: "Checo",
	"Church Slavic": "Eslavo Eclesiástico",
	Chuvash: "Chuvashian",
	Welsh: "Galés",
	Danish: "Danés",
	German: "Alemán",
	Maldivian: "Dhivehi",
	Dzongkha: "Dzongkha",
	Ewe: "Ewe",
	Greek: "Griego",
	English: "Inglés",
	Esperanto: "Esperanto",
	Spanish: "Español",
	Estonian: "Estonio",
	Basque: "Vasco",
	Faroese: "Feroés",
	Fulah: "Fula",
	Finnish: "Finlandés",
	Fijian: "Fiyiano",
	French: "Francés",
	"Western Frisian": "Frisón Occidental",
	Irish: "Irlandés",
	"Scottish Gaelic": "Gaélico Escocés",
	Galician: "Gallego",
	Guarani: "Guaraní",
	Gujarati: "Gujarati",
	Manx: "Manés",
	Hausa: "Hausa",
	Hebrew: "Hebreo",
	Hindi: "Hindi",
	Hiri: "Hiri Motu",
	Croatian: "Croata",
	"Upper Sorbian": "Sorbio Superior",
	Hungarian: "Húngaro",
	Armenian: "Armenio",
	Herero: "Herero",
	Interlingua: "Interlingua",
	Indonesian: "Indonesio",
	Interlingue: "Interlingue",
	Igbo: "Igbo",
	"Sichuan Yi": "Yi de Sichuan",
	Inupiaq: "Inupiaq",
	Icelandic: "Islandés",
	Italian: "Italiano",
	Javanese: "Javanés",
	Japanese: "Japonés",
	Kalaallisut: "Groenlandés",
	Kannada: "Kannada",
	Kashmiri: "Cachemira",
	Georgian: "Georgiano",
	CentralKanuri: "Kanuri",
	Kazakh: "Kazajo",
	Greenlandic: "Groenlandés",
	Khmer: "Jemer",
	Kikuyu: "Kikuyu",
	Kinyarwanda: "Kinyarwanda",
	Kyrgyz: "Kirguís",
	Kimbundu: "Kimbundu",
	Cornish: "Córnico",
	Kirghiz: "Kirguís",
	Kongo: "Kongo",
	Korean: "Coreano",
	Kuanyama: "Kuanyama",
	Kurdish: "Kurdo",
	Lao: "Lao",
	Latin: "Latín",
	Luxembourgish: "Luxemburgués",
	Ganda: "Luganda",
	Limburgish: "Limburgués",
	Lingala: "Lingala",
	Lithuanian: "Lituano",
	Luba: "Luba",
	Latvian: "Letón",
	Malagasy: "Malgache",
	Marshallese: "Marshalés",
	Māori: "Maorí",
	Macedonian: "Macedonio",
	Malayalam: "Malayalam",
	Mongolian: "Mongol",
	Marathi: "Marathi",
	Minangkabau: "Minangkabau",
	Maltese: "Maltés",
	Burmese: "Birmano",
	Nauru: "Nauruan",
	Nepali: "Nepalí",
	Dutch: "Neerlandés",
	Norwegian: "Noruego",
	Nynorsk: "Noruego Nynorsk",
	Navajo: "Navajo",
	"Southern Ndebele": "Ndebele Meridional",
	"Northern Ndebele": "Ndebele Septentrional",
	Ndonga: "Ndonga",
	Occitan: "Occitano",
	Ojibwa: "Ojibwa",
	Oromo: "Oromo",
	Odia: "Odia",
	Ossetic: "Osetio",
	Punjabi: "Punjabi",
	Pali: "Pali",
	Polish: "Polaco",
	Pushto: "Pastho",
	Portuguese: "Portugués",
	Quechua: "Quechua",
	Romansh: "Romanche",
	Rundi: "Rundi",
	Romanian: "Rumano",
	Russian: "Ruso",
	Kinyarwanda: "Ruandés",
	Sanskrit: "Sánscrito",
	Sardinian: "Sardo",
	Sindhi: "Sindhi",
	"Northern Sami": "Sami Septentrional",
	Sinhala: "Cingalés",
	Slovak: "Eslovaco",
	Slovenian: "Esloveno",
	Somali: "Somalí",
	Southern: "Southern",
	Sundanese: "Sundanés",
	Swahili: "Swahili",
	Swedish: "Sueco",
	Swati: "Swati",
	Siamese: "Tailandés",
	Tajik: "Tayiko",
	Tamil: "Tamil",
	Tatar: "Tatar",
	Telugu: "Telugu",
	Thai: "Tailandés",
	Tswana: "Tswana",
	Tsonga: "Tsonga",
	Turkmen: "Turcomano",
	Turkish: "Turco",
	Tumbuka: "Tumbuka",
	Twi: "Twi",
	Uighur: "Uigur",
	Ukrainian: "Ucraniano",
	Urdu: "Urdu",
	Uzbek: "Uzbeko",
	Venda: "Venda",
	Vietnamese: "Vietnamita",
	Volapük: "Volapük",
	Walloon: "Valón",
	Wolof: "Wolof",
	Xhosa: "Xhosa",
	Eastern: "Eastern",
	Yiddish: "Yídish",
	Yoruba: "Yoruba",
	Zhuang: "Zhuang",
	Chinese: "Chino",
	Zulu: "Zulu",
};

export function getLanguageNameES(englishName) {
	return languageNamesES[englishName] || englishName;
}
